main: ${PACKAGE}.CustomRecipes
name: ${NAME}
version: "${VERSION}"
api-version: "1.21"
author: winlogon
website: "${WEBSITE}"
folia-supported: true
description: "QOL upgrades to unused items and old, removed recipes."
